//ONLY ADMIN
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";

// USER

export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_FAIL = "API_CALL_FAIL";
export const UPLOAD_DATA_SUCCESS = "UPLOAD_DATA_SUCCESS";
export const UPLOAD_DATA_FAIL = "UPLOAD_DATA_FAIL";
export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";
export const SET_FILE = "SET_FILE";
export const EDIT_DATA_BEGIN = "EDIT_DATA_BEGIN";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
export const EDIT_DATA_FAIL = "EDIT_DATA_FAIL";
export const GET_ALL_EDIT_REQUEST_SUCCESS = "GET_ALL_EDIT_REQUEST_SUCCESS";
export const APPROVE_EDIT_SUCCESS = "APPROVE_EDIT_SUCCESS";
export const REJECT_EDIT_SUCCESS = "REJECT_EDIT_SUCCESS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const OPEN_SEARCH_BAR = "OPEN_SEARCH_BAR";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const GET_ALL_DELETED_DATA_SUCCESS="GET_ALL_DELETED_DATA_SUCCESS";
export const YEAR_PICKER="YEAR_PICKER";
export const IS_SEARCHED="IS_SEARCHED";
export const LAST_FILTER_QUERY="LAST_FILTER_QUERY";
export const MAKE_ACTIVITY_SUCCESS='MAKE_ACTIVITY_SUCCESS';
export const GET_ALL_ACTIVITY_SUCCESS='GET_ALL_ACTIVITY_SUCCESS';
export const DRI_ID='DRI_ID';
export const INCREASE_PAGE='INCREASE_PAGE';
export const DECREASE_PAGE='DECREASE_PAGE';
export const GET_ALL_VAR_DATA_SUCCESS='GET_ALL_VAR_DATA_SUCCESS';
export const SET_PAGE='SET_PAGE';
export const INITIAL_PAGINATION='INITIAL_PAGINATION'
export const SET_SHOW_TABLE ='SET_SHOW_TABLE';
export const TOGGLE_EXE_DATA='TOGGLE_EXE_DATA';
export const GET_ALL_IPS='GET_ALL_IPS';
export const DELETE_IP='DELETE_IP';
export const ADD_IP='ADD_IP'
export const GET_OPTION='GET_OPTION';
export const ADD_OPTION='ADD_OPTION';
export const DELETE_OPTION='DELETE_OPTION';
export const ADMIN_POPUP='ADMIN_POPUP';
export const VAR_ADMIN_POPUP='VAR_ADMIN_POPUP';
export const MAKE_DATA_EDITABLE='MAKE_DATA_EDITABLE';
export const GET_SINGLE_DATA_SUCCESS='GET_SINGLE_DATA_SUCCESS';
export const GET_ALL_ACTIVITY_SUCCESS_VAR='GET_ALL_ACTIVITY_SUCCESS_VAR'






